title: LiteCore Document
description: シンプル、軽量、高速なオペレーティングシステムLiteCoreのドキュメント


domain: core.nekogakure.jp
url: https://core.nekogakure.jp
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme